aliyun:
  oss:
    endpoint: zxxtyzy.oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI4GKh3GFGyaLHSkS6LFTG
    accessKeySecret: XvDCVT9c29ZIZD2iAvbh2y5anKEjiA
    bucketName: zxxtyzy
#    urlPrefix: https://preview.itdung.cn/
    bucketUrl: http://zxxtyzy.oss-cn-shanghai.aliyuncs.com/
  sms:
    accessKeyId: LTAI4G2Fwi7Xe6hDyQHtBXax
    accessKeySecret: gCXQX26SF5QE4fDOfVDHIAk0K0IKD9
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    endpointName: cn-hangzhou
    signName: 南京智体信息科技有限公司
    codeTemplate: SMS_208735069
    version: 2017-05-25
    action: SendSms

server:
  port: 8688
  tomcat:
    max-swallow-size: 200MB
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 42.193.47.74
    port: 6379
    database: 0
    password: Njhykj/388
    jedis:
      pool:
        #最大连接数量
        max-active: 200
        #最大空闲数量
        max-idle: 200
        #最小空闲数量
        min-idle: 10
        #最大等待时间
        max-wait: 3000ms
#存储预览pdf的临时目录
preview:
  temporary_preview_path: /home/previewpdf/
file:
  locationTemp: /home/locationTempProd/
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

